###
GET localhost:8081/hello

###
POST localhost:8081/create

###
POST localhost:8082/create

###
GET localhost:8081/info/101

###
GET localhost:8082/info/201

###
POST localhost:8071/update/0001/101/808/refill

###
POST localhost:8071/update/0003/201/606/refill

###
POST localhost:8071/update/0005/201/-6/withdraw

###
POST localhost:8071/update/0004/301/202/refill

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "transferId": 90005,
  "sourceId": 101,
  "destinationId": 201,
  "value": 308,
  "category": "taxi"
}

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "transferId": 90003,
  "sourceId": 201,
  "destinationId": 301,
  "value": 128,
  "category": "supermarket"
}