version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -Xms128m -Xmx256m
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_HOSTNAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  account-service1:
    image: account-service1
    container_name: account-service1
    build:
      dockerfile: ./docker/DockerfileAccount
      context: ../
    environment:
      APP_PORT: 8081
      ACCOUNT_ID: 1
    ports:
      - 8081:8080

  account-service2:
    image: account-service2
    container_name: account-service2
    build:
      dockerfile: ./docker/DockerfileAccount
      context: ../
    environment:
      APP_PORT: 8082
      ACCOUNT_ID: 2
    ports:
      - 8082:8080

  operation-service:
    image: operation-service
    container_name: operation-service
    build:
      dockerfile: ./docker/DockerfileOperation
      context: ../
    environment:
      APP_PORT: 8071
    ports:
      - 8071:8080